import sharp from 'sharp';

/**
 * EU AI Act Art. 50: AI-generated images must be marked in a machine-readable
 * way (and, for synthetic media of real people, disclosed). We embed EXIF
 * identifying the synthetic source — IPTC `digitalSourceType: trainedAlgorithmicMedia`,
 * the recognized "AI-generated" value platforms/detectors read — and optionally
 * composite a subtle visible badge.
 *
 * Apply ONLY to genuinely AI-generated images (selfies, avatar packs) — never to
 * real user uploads. And NEVER route these through a metadata-stripping pipeline
 * (e.g. the estate's stripImageMetadata): that erases the mandatory marking.
 *
 * Marking must never break generation: any failure falls back to the raw buffer.
 */

const AI_DESCRIPTION =
  'AI-generated synthetic image (not a real photograph). digitalSourceType: trainedAlgorithmicMedia. Generated by Echo.';

// Visible badge is an aesthetic choice on a memorial product — off by default,
// flip on with IMAGE_VISIBLE_WATERMARK=true. The EXIF mark below is always applied.
const VISIBLE = process.env.IMAGE_VISIBLE_WATERMARK === 'true';
const LABEL = process.env.IMAGE_WATERMARK_LABEL || 'AI';

export async function markGeneratedImage(buf: Buffer): Promise<Buffer> {
  try {
    let pipeline = sharp(buf, { failOn: 'none' });

    if (VISIBLE) {
      const meta = await sharp(buf, { failOn: 'none' }).metadata();
      const w = meta.width ?? 1024;
      const pad = Math.round(w * 0.022);
      const fontSize = Math.max(14, Math.round(w * 0.034));
      const svg = Buffer.from(
        `<svg width="${w}" height="${fontSize + pad * 2}" xmlns="http://www.w3.org/2000/svg">` +
          `<text x="${w - pad}" y="${fontSize + pad / 2}" text-anchor="end" ` +
          `font-family="Helvetica, Arial, sans-serif" font-size="${fontSize}" font-weight="600" ` +
          `fill="#ffffff" fill-opacity="0.78" stroke="#000000" stroke-opacity="0.35" ` +
          `stroke-width="${Math.max(1, fontSize / 22)}" paint-order="stroke">✦ ${LABEL}</text>` +
          `</svg>`,
      );
      const composited = await pipeline
        .composite([{ input: svg, gravity: 'southeast' }])
        .toBuffer();
      pipeline = sharp(composited, { failOn: 'none' });
    }

    return await pipeline
      .withExif({
        IFD0: {
          Software: 'Echo (AI-generated synthetic media)',
          ImageDescription: AI_DESCRIPTION,
          Copyright: 'AI-generated synthetic media',
        },
      })
      .jpeg({ quality: 92 })
      .toBuffer();
  } catch {
    return buf;
  }
}
